### ISSUE TITLE
Backend settings error

### ISSUE THREAD

**Issue by quentaro81** [gruz/AutoReadMore#2]
Hi, im using Joomla 3.9, and auto read more 4.5.25, get this error massage, thank you for the answer/solution.

Call to protected method GJFieldsFormFieldNoteFixed::getInput() from context 'GJFieldsFormFieldVariablefield'

**Comment by gruz** [comment]
Hi. I tested at my localhost and could not reproduce the issue.

Try installing the latest gjfields 
https://gruz.ml/en/extensions/gjfields-sefl-reproducing-joomla-jform-fields.html

If this doesn't help, to test/fix the issue I need your web-site copy (akeebabackup of your Joomla or a superadmin access so I can make akeebabackup myself) to quickly reproduce exactly your data and configuration. Please consider excluding heavy files (images, videos) from the akeebabackup if possible. 

Please also provide exact steps to reproduce the problem.

Mail me to arygroup@gmail.com

**Comment by gruz** [comment]
Fixed. GJFields library updated.
