### ISSUE TITLE
Joomla 4

### ISSUE THREAD

**Issue by darekmer** [gruz/AutoReadMore#3]
Hello, will there be a new version for Joomla 4?

**Comment by gruz** [comment]
I'm not sure. I don't use Joomla anymore so I don't need the plugin for my own purposes. And I don't have any other  motivation to work on it. So maybe later I will work on it, but I cannot promise.

**Comment by conseilgouz** [comment]
Hi,

Just created a Joomla 3.10 / Joomla 4 version of this plugin : https://github.com/conseilgouz/AutoReadMore-J4

For information,  your readme.md is pointing to a messy website. Please remove it.

Pascal

**Comment by gruz** [comment]
Cool!

It was my web-site. But the domain was taken by some bad guys :-(


Updated readme with your link, @conseilgouz 

Thanks.
